name: Release
on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - main
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download
        uses: dawidd6/action-download-artifact@v10
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          use_unzip: true

      - name: Version
        run: |
          touch .env
          echo QT_VERSION=$(<version.txt) >> .env

      - name: Info
        run: |
          ls -aohR
          echo QT_VERSION=$QT_VERSION

#      - name: Release
#        uses: softprops/action-gh-release@v2
#        if: false
#        with:
#          body: "Qt release ${{env.QT_VERSION}}"
#          files: qt-${{env.QT_VERSION}}-msvc2022-x64.7z
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
